### ISSUE TITLE
application.yml이 .gitignore되지 않는 문제 발견

### ISSUE THREAD

**Issue by Yejining** [AntAlbum/AntAlbum#17]
## 버그 내용
.gitignore에 추가한 application.yml이 적용되지 않아 민감한 정보가 커밋되는 문제가 발생했습니다.
 
## 재현 과정
1. .gitignore에 application.yml 추가
2. application.yml이 ignore되지 않아 커밋되는 문제 발생

## 우려 사항
- AWS 키 탈취....

**Comment by rnrlgus** [comment]
PR#18 확인 부탁드립니다.

**Comment by Yejining** [comment]
> PR#18 확인 부탁드립니다.

확인 & 머지 완료했습니다~
